/*
 * This file is generated by jOOQ.
 */
package com.comesample.ktor.jooq.tables;


import com.comesample.ktor.jooq.JUserAccess;
import com.comesample.ktor.jooq.Keys;
import com.comesample.ktor.jooq.tables.records.JPromocodesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPromocodes extends TableImpl<JPromocodesRecord> {

    private static final long serialVersionUID = 621549701;

    /**
     * The reference instance of <code>user_access.promocodes</code>
     */
    public static final JPromocodes PROMOCODES = new JPromocodes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JPromocodesRecord> getRecordType() {
        return JPromocodesRecord.class;
    }

    /**
     * The column <code>user_access.promocodes.uuid</code>.
     */
    public final TableField<JPromocodesRecord, UUID> UUID = createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>user_access.promocodes.value</code>.
     */
    public final TableField<JPromocodesRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>user_access.promocodes.external_user_uuid</code>.
     */
    public final TableField<JPromocodesRecord, UUID> EXTERNAL_USER_UUID = createField(DSL.name("external_user_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>user_access.promocodes.created_at</code>.
     */
    public final TableField<JPromocodesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>user_access.promocodes.updated_at</code>.
     */
    public final TableField<JPromocodesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>user_access.promocodes.deleted_at</code>.
     */
    public final TableField<JPromocodesRecord, LocalDateTime> DELETED_AT = createField(DSL.name("deleted_at"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>user_access.promocodes</code> table reference
     */
    public JPromocodes() {
        this(DSL.name("promocodes"), null);
    }

    /**
     * Create an aliased <code>user_access.promocodes</code> table reference
     */
    public JPromocodes(String alias) {
        this(DSL.name(alias), PROMOCODES);
    }

    /**
     * Create an aliased <code>user_access.promocodes</code> table reference
     */
    public JPromocodes(Name alias) {
        this(alias, PROMOCODES);
    }

    private JPromocodes(Name alias, Table<JPromocodesRecord> aliased) {
        this(alias, aliased, null);
    }

    private JPromocodes(Name alias, Table<JPromocodesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> JPromocodes(Table<O> child, ForeignKey<O, JPromocodesRecord> key) {
        super(child, key, PROMOCODES);
    }

    @Override
    public Schema getSchema() {
        return JUserAccess.USER_ACCESS;
    }

    @Override
    public UniqueKey<JPromocodesRecord> getPrimaryKey() {
        return Keys.PROMOCODES_PKEY;
    }

    @Override
    public List<UniqueKey<JPromocodesRecord>> getKeys() {
        return Arrays.<UniqueKey<JPromocodesRecord>>asList(Keys.PROMOCODES_PKEY, Keys.PROMOCODES_VALUE_KEY, Keys.PROMOCODES_EXTERNAL_USER_UUID_KEY);
    }

    @Override
    public List<ForeignKey<JPromocodesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<JPromocodesRecord, ?>>asList(Keys.PROMOCODES__PROMOCODES_EXTERNAL_USER_UUID_FKEY);
    }

    public JUsers users() {
        return new JUsers(this, Keys.PROMOCODES__PROMOCODES_EXTERNAL_USER_UUID_FKEY);
    }

    @Override
    public JPromocodes as(String alias) {
        return new JPromocodes(DSL.name(alias), this);
    }

    @Override
    public JPromocodes as(Name alias) {
        return new JPromocodes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JPromocodes rename(String name) {
        return new JPromocodes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JPromocodes rename(Name name) {
        return new JPromocodes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, UUID, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
