###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/hello?start=50&end=100&maybe=1
Content-Type: application/json

{"name":  "kekw"}

###