/*
 * This file is generated by jOOQ.
 */
package com.comesample.ktor.jooq.tables.records;


import com.comesample.ktor.jooq.tables.JPromocodes;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPromocodesRecord extends UpdatableRecordImpl<JPromocodesRecord> implements Record6<UUID, String, UUID, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1162771840;

    /**
     * Setter for <code>user_access.promocodes.uuid</code>.
     */
    public JPromocodesRecord setUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user_access.promocodes.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>user_access.promocodes.value</code>.
     */
    public JPromocodesRecord setValue(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user_access.promocodes.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_access.promocodes.external_user_uuid</code>.
     */
    public JPromocodesRecord setExternalUserUuid(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user_access.promocodes.external_user_uuid</code>.
     */
    public UUID getExternalUserUuid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>user_access.promocodes.created_at</code>.
     */
    public JPromocodesRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user_access.promocodes.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>user_access.promocodes.updated_at</code>.
     */
    public JPromocodesRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user_access.promocodes.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>user_access.promocodes.deleted_at</code>.
     */
    public JPromocodesRecord setDeletedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>user_access.promocodes.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, UUID, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, UUID, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JPromocodes.PROMOCODES.UUID;
    }

    @Override
    public Field<String> field2() {
        return JPromocodes.PROMOCODES.VALUE;
    }

    @Override
    public Field<UUID> field3() {
        return JPromocodes.PROMOCODES.EXTERNAL_USER_UUID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return JPromocodes.PROMOCODES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JPromocodes.PROMOCODES.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return JPromocodes.PROMOCODES.DELETED_AT;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public UUID component3() {
        return getExternalUserUuid();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getDeletedAt();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public UUID value3() {
        return getExternalUserUuid();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getDeletedAt();
    }

    @Override
    public JPromocodesRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public JPromocodesRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public JPromocodesRecord value3(UUID value) {
        setExternalUserUuid(value);
        return this;
    }

    @Override
    public JPromocodesRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public JPromocodesRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public JPromocodesRecord value6(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public JPromocodesRecord values(UUID value1, String value2, UUID value3, LocalDateTime value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JPromocodesRecord
     */
    public JPromocodesRecord() {
        super(JPromocodes.PROMOCODES);
    }

    /**
     * Create a detached, initialised JPromocodesRecord
     */
    public JPromocodesRecord(UUID uuid, String value, UUID externalUserUuid, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        super(JPromocodes.PROMOCODES);

        set(0, uuid);
        set(1, value);
        set(2, externalUserUuid);
        set(3, createdAt);
        set(4, updatedAt);
        set(5, deletedAt);
    }
}
