/*
 * This file is generated by jOOQ.
 */
package com.comesample.ktor.jooq;


import com.comesample.ktor.jooq.tables.JPromocodes;
import com.comesample.ktor.jooq.tables.JUsers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JUserAccess extends SchemaImpl {

    private static final long serialVersionUID = -766552978;

    /**
     * The reference instance of <code>user_access</code>
     */
    public static final JUserAccess USER_ACCESS = new JUserAccess();

    /**
     * The table <code>user_access.promocodes</code>.
     */
    public final JPromocodes PROMOCODES = JPromocodes.PROMOCODES;

    /**
     * The table <code>user_access.users</code>.
     */
    public final JUsers USERS = JUsers.USERS;

    /**
     * No further instances allowed
     */
    private JUserAccess() {
        super("user_access", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            JPromocodes.PROMOCODES,
            JUsers.USERS);
    }
}
