/*
 * This file is generated by jOOQ.
 */
package com.comesample.ktor.jooq;


import com.comesample.ktor.jooq.tables.JPromocodes;
import com.comesample.ktor.jooq.tables.JUsers;
import com.comesample.ktor.jooq.tables.records.JPromocodesRecord;
import com.comesample.ktor.jooq.tables.records.JUsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>user_access</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JPromocodesRecord> PROMOCODES_PKEY = UniqueKeys0.PROMOCODES_PKEY;
    public static final UniqueKey<JPromocodesRecord> PROMOCODES_VALUE_KEY = UniqueKeys0.PROMOCODES_VALUE_KEY;
    public static final UniqueKey<JPromocodesRecord> PROMOCODES_EXTERNAL_USER_UUID_KEY = UniqueKeys0.PROMOCODES_EXTERNAL_USER_UUID_KEY;
    public static final UniqueKey<JUsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<JPromocodesRecord, JUsersRecord> PROMOCODES__PROMOCODES_EXTERNAL_USER_UUID_FKEY = ForeignKeys0.PROMOCODES__PROMOCODES_EXTERNAL_USER_UUID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<JPromocodesRecord> PROMOCODES_PKEY = Internal.createUniqueKey(JPromocodes.PROMOCODES, "promocodes_pkey", new TableField[] { JPromocodes.PROMOCODES.UUID }, true);
        public static final UniqueKey<JPromocodesRecord> PROMOCODES_VALUE_KEY = Internal.createUniqueKey(JPromocodes.PROMOCODES, "promocodes_value_key", new TableField[] { JPromocodes.PROMOCODES.VALUE }, true);
        public static final UniqueKey<JPromocodesRecord> PROMOCODES_EXTERNAL_USER_UUID_KEY = Internal.createUniqueKey(JPromocodes.PROMOCODES, "promocodes_external_user_uuid_key", new TableField[] { JPromocodes.PROMOCODES.EXTERNAL_USER_UUID }, true);
        public static final UniqueKey<JUsersRecord> USERS_PKEY = Internal.createUniqueKey(JUsers.USERS, "users_pkey", new TableField[] { JUsers.USERS.UUID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<JPromocodesRecord, JUsersRecord> PROMOCODES__PROMOCODES_EXTERNAL_USER_UUID_FKEY = Internal.createForeignKey(Keys.USERS_PKEY, JPromocodes.PROMOCODES, "promocodes_external_user_uuid_fkey", new TableField[] { JPromocodes.PROMOCODES.EXTERNAL_USER_UUID }, true);
    }
}
