/*
 * This file is generated by jOOQ.
 */
package com.comesample.ktor.jooq;


import com.comesample.ktor.jooq.tables.JPromocodes;
import com.comesample.ktor.jooq.tables.JUsers;


/**
 * Convenience access to all tables in user_access
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user_access.promocodes</code>.
     */
    public static final JPromocodes PROMOCODES = JPromocodes.PROMOCODES;

    /**
     * The table <code>user_access.users</code>.
     */
    public static final JUsers USERS = JUsers.USERS;
}
