# Generated by Django 4.0.3 on 2022-03-24 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_webpage_accessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 10, 7, 35, 20925, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
