# Generated by Django 4.0.3 on 2022-03-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_lead',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='app.employee'),
        ),
    ]
